### ISSUE TITLE
Todo page

### ISSUE THREAD

**Issue by KimBuyCookies** [Team-Easily/Easily#25]
- [ ] Create list
- [ ] add new task
- [ ] delete completed tasks
- [ ] add check off box
- [ ] display all tasks
